"""initial migration

Revision ID: 132614894e13
Revises: 
Create Date: 2025-04-11 23:39:57.710249

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132614894e13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('author_bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_author_name'), 'author', ['author_name'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('category_desc', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_category_name'), 'category', ['category_name'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('book_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('book_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('book_cover_photo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_author_id'), 'book', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_category_id'), 'book', ['category_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('discount_start_date', sa.Date(), nullable=False),
    sa.Column('discount_end_date', sa.Date(), nullable=False),
    sa.Column('discount_price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_book_id'), 'discount', ['book_id'], unique=False)
    op.create_table('orderitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitem_book_id'), 'orderitem', ['book_id'], unique=False)
    op.create_index(op.f('ix_orderitem_order_id'), 'orderitem', ['order_id'], unique=False)
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('review_title', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('review_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('review_star', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_book_id'), 'review', ['book_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_book_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_orderitem_order_id'), table_name='orderitem')
    op.drop_index(op.f('ix_orderitem_book_id'), table_name='orderitem')
    op.drop_table('orderitem')
    op.drop_index(op.f('ix_discount_book_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_book_category_id'), table_name='book')
    op.drop_index(op.f('ix_book_author_id'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_category_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_author_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
